GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "First Title",
    "author": "John DiFelice",
    "url": "http://",
    "likes": "5"
}